credentials:
  usernames:
    admin:
      email: planejamento.visa@suzantur.com.br
      name: Administrador
      # Hash da senha: Pl@n3j@m3nt0
      # Gerado usando: python gerar_hash_senha.py
      password: $2b$12$qwsjDSUL8bo7lhg927jYtuGEht.inzukf.TBSeDLmi47K3cvpMFaq
    claudinei:
      email: claudinei@suzantur.com.br
      name: Claudinei
      # Hash da senha: Cl@udin3iIt@p3mirim
      # Gerado usando: python gerar_hash_senha.py
      password: $2b$12$yVI/DAreu9gqwnfSA76CXeuIoz3ACNmP8HlIQIEJ/ZQGNpGISIVb.
    manutencao:
      email: manutencao@suzantur.com.br
      name: Manutenção
      # Hash da senha: M@n@ut3nc@0It@p3mirim
      # Gerado usando: python gerar_hash_senha.py
      password: $2b$12$GPiGTN6PCPc3esLJGdEFieX9UopShrtG1H0etrrk7baeNJpKWA1r
cookie:
  expiry_days: 30
  key: checklist_vistoria_key_12345
  name: checklist_vistoria_cookie
preauthorized:
  emails:
    - planejamento.visa@suzantur.com.br
    - claudinei@suzantur.com.br
    - manutencao@suzantur.com.br
